global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
    # nginx-exporter
      - targets: ['exporter-nginx-proxy-01:9113', 'exporter-nginx-proxy-02:9113', 'exporter-nginx-lb:9113']
    # node-exporter  
      - targets: ['node-exporter:9100']